import { Report, ReportCategory, ReportDataType } from './types';
import {
  FileText,
  CreditCard,
  Users,
  DollarSign,
  Briefcase,
  BarChart4,
  UserCheck,
  TrendingUp,
  User,
  TestTube,
  Bug,
  Calculator,
  Building2,
  Package,
} from 'lucide-react';

export const reportCategories = [
  { id: 'all', label: 'All', icon: FileText },
  // {
  //   id: 'billings',
  //   label: 'Billings and Collections',
  //   icon: CreditCard,
  //   submenus: [
  //     {
  //       id: 'ar_turnover',
  //       label: 'AR Turnover Ratio',
  //       chartKey: 'ar_turnover',
  //     },
  //     { id: 'ar_aging', label: 'AR Aging', chartKey: 'ar_aging' },
  //     {
  //       id: 'avg_collection',
  //       label: 'Average Collection Period',
  //       chartKey: 'avg_collection',
  //     },
  //     { id: 'bill_rate', label: 'Bill Rate', chartKey: 'bill_rate' },
  //     {
  //       id: 'billable_util',
  //       label: 'Billable Utilization Rate',
  //       chartKey: 'billable_util',
  //     },
  //     {
  //       id: 'collections_effectiveness',
  //       label: 'Collections Effectiveness Index',
  //       chartKey: 'collections_effectiveness',
  //     },
  //     { id: 'collections', label: 'Collections', chartKey: 'collections' },
  //     { id: 'dso', label: 'Days Sales Outstanding', chartKey: 'dso' },
  //   ],
  // },
  // {
  //   id: 'bookings',
  //   label: 'Bookings and Customers',
  //   icon: Users,
  //   submenus: [
  //     { id: 'acl', label: 'Average Contract Length (ACL)', chartKey: 'acl' },
  //     { id: 'asp', label: 'Average Sale Price (ASP)', chartKey: 'asp' },
  //     {
  //       id: 'cac_payback',
  //       label: 'CAC Payback Period',
  //       chartKey: 'cac_payback',
  //     },
  //     { id: 'churn_rate', label: 'Churn Rate', chartKey: 'churn_rate' },
  //     {
  //       id: 'cost_to_serve',
  //       label: 'Cost to Serve',
  //       chartKey: 'cost_to_serve',
  //     },
  //     {
  //       id: 'customer_count',
  //       label: 'Customer Count',
  //       chartKey: 'customer_count',
  //     },
  //     {
  //       id: 'customer_retention_cost',
  //       label: 'Customer Retention Cost',
  //       chartKey: 'customer_retention_cost',
  //     },
  //     {
  //       id: 'negative_churn',
  //       label: 'Negative Churn',
  //       chartKey: 'negative_churn',
  //     },
  //     { id: 'ltv_cac', label: 'LTV/CAC Ratio', chartKey: 'ltv_cac' },
  //     {
  //       id: 'logo_retention',
  //       label: 'Logo Retention',
  //       chartKey: 'logo_retention',
  //     },
  //     { id: 'renewal_rate', label: 'Renewal Rate', chartKey: 'renewal_rate' },
  //     { id: 'bookings', label: 'Bookings', chartKey: 'bookings' },
  //     {
  //       id: 'customer_attrition',
  //       label: 'Customer Attrition',
  //       chartKey: 'customer_attrition',
  //     },
  //   ],
  // },
  // {
  //   id: 'cashflow',
  //   label: 'Cashflow and Expenses',
  //   icon: DollarSign,
  //   submenus: [
  //     { id: 'ap_aging', label: 'AP Aging', chartKey: 'ap_aging' },
  //     {
  //       id: 'ap_turnover',
  //       label: 'AP Turnover Ratio',
  //       chartKey: 'ap_turnover',
  //     },
  //     {
  //       id: 'burn_multiple',
  //       label: 'Burn Multiple',
  //       chartKey: 'burn_multiple',
  //     },
  //     {
  //       id: 'capital_efficiency',
  //       label: 'Capital Efficiency',
  //       chartKey: 'capital_efficiency',
  //     },
  //     {
  //       id: 'cfoa',
  //       label: 'Cash Flow from Operating Activities',
  //       chartKey: 'cfoa',
  //     },
  //     { id: 'dpo', label: 'Days Payable Outstanding', chartKey: 'dpo' },
  //     { id: 'gross_margin', label: 'Gross Margin', chartKey: 'gross_margin' },
  //     {
  //       id: 'expense_dashboard',
  //       label: 'Expense Dashboard',
  //       chartKey: 'expense_dashboard',
  //     },
  //     { id: 'net_burn', label: 'Net Burn', chartKey: 'net_burn' },
  //     {
  //       id: 'rnd_payback',
  //       label: 'R&D Payback Ratio',
  //       chartKey: 'rnd_payback',
  //     },
  //     { id: 'ebitda', label: 'EBITDA', chartKey: 'ebitda' },
  //   ],
  // },
  // {
  //   id: 'headcount',
  //   label: 'Headcount',
  //   icon: UserCheck,
  //   submenus: [
  //     { id: 'headcount', label: 'Headcount', chartKey: 'headcount' },
  //     {
  //       id: 'accrued_payroll',
  //       label: 'Accrued Payroll Cost',
  //       chartKey: 'accrued_payroll',
  //     },
  //     {
  //       id: 'fully_burdened_labor',
  //       label: 'Fully Burdened Labor Rate',
  //       chartKey: 'fully_burdened_labor',
  //     },
  //     {
  //       id: 'hr_to_employee',
  //       label: 'HR to Employee Ratio',
  //       chartKey: 'hr_to_employee',
  //     },
  //     {
  //       id: 'headcount_metrics',
  //       label: 'Headcount Metrics',
  //       chartKey: 'headcount_metrics',
  //     },
  //     {
  //       id: 'cost_of_labor',
  //       label: 'Cost of Labor',
  //       chartKey: 'cost_of_labor',
  //     },
  //     {
  //       id: 'employee_turnover',
  //       label: 'Employee Turnover Metrics',
  //       chartKey: 'employee_turnover',
  //     },
  //     {
  //       id: 'workforce_planning',
  //       label: 'Workforce Planning Metrics',
  //       chartKey: 'workforce_planning',
  //     },
  //   ],
  // },
  // {
  //   id: 'revenue',
  //   label: 'Revenue, ARR and MRR',
  //   icon: TrendingUp,
  //   submenus: [
  //     {
  //       id: 'accrued_revenue',
  //       label: 'Accrued Revenue',
  //       chartKey: 'accrued_revenue',
  //     },
  //     { id: 'arr', label: 'Annual Recurring Revenue (ARR)', chartKey: 'arr' },
  //     { id: 'mrr', label: 'Monthly Recurring Revenue (MRR)', chartKey: 'mrr' },
  //     { id: 'gross_sales', label: 'Gross Sales', chartKey: 'gross_sales' },
  //     {
  //       id: 'deferred_revenue',
  //       label: 'Deferred Revenue',
  //       chartKey: 'deferred_revenue',
  //     },
  //     {
  //       id: 'pipeline_coverage',
  //       label: 'Pipeline Coverage Ratio',
  //       chartKey: 'pipeline_coverage',
  //     },
  //     {
  //       id: 'projected_revenue',
  //       label: 'Projected Revenue',
  //       chartKey: 'projected_revenue',
  //     },
  //     {
  //       id: 'revenue_backlog',
  //       label: 'Revenue Backlog',
  //       chartKey: 'revenue_backlog',
  //     },
  //     {
  //       id: 'revenue_per_employee',
  //       label: 'Revenue Per Employee',
  //       chartKey: 'revenue_per_employee',
  //     },
  //     { id: 'rule_of_40', label: 'Rule of 40', chartKey: 'rule_of_40' },
  //     { id: 'tcv', label: 'Total Contract Value (TCV)', chartKey: 'tcv' },
  //     {
  //       id: 'rpo',
  //       label: 'Remaining Performance Obligation (RPO)',
  //       chartKey: 'rpo',
  //     },
  //     {
  //       id: 'unearned_revenue',
  //       label: 'Unearned Revenue',
  //       chartKey: 'unearned_revenue',
  //     },
  //     {
  //       id: 'weighted_pipeline',
  //       label: 'Weighted Pipeline / Revenue',
  //       chartKey: 'weighted_pipeline',
  //     },
  //   ],
  // },
  // {
  //   id: 'sales',
  //   label: 'Sales Performance',
  //   icon: BarChart4,
  //   submenus: [
  //     {
  //       id: 'avg_deal_size',
  //       label: 'Average Deal Size',
  //       chartKey: 'avg_deal_size',
  //     },
  //     {
  //       id: 'avg_sales_cycle',
  //       label: 'Average Sales Cycle',
  //       chartKey: 'avg_sales_cycle',
  //     },
  //     {
  //       id: 'closed_won_lost',
  //       label: 'Closed Won/Lost Summary',
  //       chartKey: 'closed_won_lost',
  //     },
  //     { id: 'closing_rate', label: 'Closing Rate', chartKey: 'closing_rate' },
  //     {
  //       id: 'cost_per_lead',
  //       label: 'Cost Per Lead',
  //       chartKey: 'cost_per_lead',
  //     },
  //     {
  //       id: 'cost_per_opportunity',
  //       label: 'Cost Per Opportunity',
  //       chartKey: 'cost_per_opportunity',
  //     },
  //     {
  //       id: 'pipeline_generation',
  //       label: 'Pipeline Generation',
  //       chartKey: 'pipeline_generation',
  //     },
  //     { id: 'roas', label: 'Return on Ad Spend (ROAS)', chartKey: 'roas' },
  //     {
  //       id: 'sales_conversion_rate',
  //       label: 'Sales Conversion Rate',
  //       chartKey: 'sales_conversion_rate',
  //     },
  //     {
  //       id: 'sales_funnel',
  //       label: 'Sales Funnel Metrics',
  //       chartKey: 'sales_funnel',
  //     },
  //     {
  //       id: 'quota_attainment',
  //       label: 'Quota Attainment',
  //       chartKey: 'quota_attainment',
  //     },
  //     {
  //       id: 'sales_rep_ramp',
  //       label: 'Sales Rep Ramp',
  //       chartKey: 'sales_rep_ramp',
  //     },
  //     {
  //       id: 'sales_velocity',
  //       label: 'Sales Velocity',
  //       chartKey: 'sales_velocity',
  //     },
  //     {
  //       id: 'sales_funnel_conversion',
  //       label: 'Sales Funnel Conversion Rate',
  //       chartKey: 'sales_funnel_conversion',
  //     },
  //   ],
  // },
  {
    id: 'financial_analytics',
    label: 'Financial Analytics',
    icon: BarChart4,
    submenus: [
      {
        id: 'revenue_overview',
        label: 'Revenue Overview',
        chartKey: 'revenue_overview',
        factName: 'revenue',
        metrics: ['total_revenue'],
        dimensions: ['time'],
      },
      {
        id: 'revenue_by_customer',
        label: 'Revenue by Customer',
        chartKey: 'revenue_by_customer',
        factName: 'revenue',
        metrics: ['total_revenue'],
        dimensions: ['time', 'customer'],
      },
      {
        id: 'revenue_by_product',
        label: 'Revenue by Product',
        chartKey: 'revenue_by_product',
        factName: 'revenue',
        metrics: ['total_revenue'],
        dimensions: ['time', 'product'],
      },
      {
        id: 'expense_overview',
        label: 'Expense Overview',
        chartKey: 'expense_overview',
        factName: 'opex',
        metrics: ['total_opex_amount'],
        dimensions: ['time'],
      },
      {
        id: 'cogs_overview',
        label: 'Cost of Goods Sold',
        chartKey: 'cogs_overview',
        factName: 'cogs',
        metrics: ['total_cost'],
        dimensions: ['time'],
      },
      {
        id: 'net_income',
        label: 'Net Income',
        chartKey: 'net_income',
        factName: 'net_income',
        metrics: ['net_income_after_tax'],
        dimensions: ['time'],
      },
      {
        id: 'cash_flow',
        label: 'Cash Flow',
        chartKey: 'cash_flow',
        factName: 'cash_equivalent',
        metrics: ['net_cash_movement'],
        dimensions: ['time'],
      },
      {
        id: 'ar_balance',
        label: 'Accounts Receivable',
        chartKey: 'ar_balance',
        factName: 'ar_balance',
        metrics: ['customer_running_balance'],
        dimensions: ['time'],
      },
      {
        id: 'ap_balance',
        label: 'Accounts Payable',
        chartKey: 'ap_balance',
        factName: 'ap_balance',
        metrics: ['vendor_running_balance'],
        dimensions: ['time'],
      },
    ],
  },
  {
    id: 'revenue_analytics',
    label: 'Revenue Analytics',
    icon: TrendingUp,
    submenus: [
      {
        id: 'revenue_overview',
        label: 'Revenue Overview',
        chartKey: 'revenue_overview',
        factName: 'revenue',
        metrics: ['total_revenue'],
        dimensions: ['time'],
      },
      {
        id: 'revenue_by_customer',
        label: 'Revenue by Customer',
        chartKey: 'revenue_by_customer',
        factName: 'revenue',
        metrics: ['total_revenue'],
        dimensions: ['time', 'customer'],
      },
      {
        id: 'revenue_by_product',
        label: 'Revenue by Product',
        chartKey: 'revenue_by_product',
        factName: 'revenue',
        metrics: ['total_revenue'],
        dimensions: ['time', 'product'],
      },
      {
        id: 'revenue_by_account',
        label: 'Revenue by Account',
        chartKey: 'revenue_by_account',
        factName: 'revenue',
        metrics: ['total_revenue'],
        dimensions: ['time', 'account'],
      },
    ],
  },
  {
    id: 'expense_analytics',
    label: 'Expense Analytics',
    icon: DollarSign,
    submenus: [
      {
        id: 'opex_overview',
        label: 'Operating Expenses',
        chartKey: 'opex_overview',
        factName: 'opex',
        metrics: ['total_opex_amount'],
        dimensions: ['time'],
      },
      {
        id: 'cogs_overview',
        label: 'Cost of Goods Sold',
        chartKey: 'cogs_overview',
        factName: 'cogs',
        metrics: ['total_cost'],
        dimensions: ['time'],
      },
      {
        id: 'cogs_by_product',
        label: 'COGS by Product',
        chartKey: 'cogs_by_product',
        factName: 'cogs',
        metrics: ['total_cost'],
        dimensions: ['time', 'product'],
      },
      {
        id: 'cogs_by_vendor',
        label: 'COGS by Vendor',
        chartKey: 'cogs_by_vendor',
        factName: 'cogs',
        metrics: ['total_cost'],
        dimensions: ['time', 'vendor'],
      },
    ],
  },
  {
    id: 'human_capital',
    label: 'Human Capital Analytics',
    icon: Building2,
    submenus: [
      {
        id: 'headcount_overview',
        label: 'Headcount Overview',
        chartKey: 'headcount_overview',
        factName: 'headcount',
        metrics: ['headcount', 'total_fte'],
        dimensions: ['time'],
        module: 'human_capital',
      },
      {
        id: 'headcount_by_role',
        label: 'Headcount by Role',
        chartKey: 'headcount_by_role',
        factName: 'headcount',
        metrics: ['headcount'],
        dimensions: ['time', 'role'],
        module: 'human_capital',
      },
      {
        id: 'payroll_overview',
        label: 'Payroll Overview',
        chartKey: 'payroll_overview',
        factName: 'salary_expenses_monthly',
        metrics: ['total_salary_expense', 'cost_per_fte'],
        dimensions: ['time'],
        module: 'human_capital',
      },
      {
        id: 'payroll_by_employment_type',
        label: 'Payroll by Employment Type',
        chartKey: 'payroll_by_employment_type',
        factName: 'salary_expenses',
        metrics: ['gross_salary'],
        dimensions: ['time', 'role'],
        module: 'human_capital',
      },
      {
        id: 'salary_expenses',
        label: 'Salary Expenses',
        chartKey: 'salary_expenses',
        factName: 'salary_expenses',
        metrics: ['gross_salary', 'base_pay'],
        dimensions: ['time', 'role'],
        module: 'human_capital',
      },
      {
        id: 'benefit_expenses',
        label: 'Benefit Expenses',
        chartKey: 'benefit_expenses',
        factName: 'benefit_expenses_monthly',
        metrics: ['benefit_amount', 'value'],
        dimensions: ['time', 'role'],
        module: 'human_capital',
      },
    ],
  },
  {
    id: 'sales_inventory',
    label: 'Sales & Inventory Analytics',
    icon: Package,
    submenus: [
      {
        id: 'sales_overview',
        label: 'Sales Overview',
        chartKey: 'sales_overview',
        factName: 'units_sold',
        metrics: ['total_units_sold', 'total_revenue'],
        dimensions: ['time'],
        module: 'sales_inventory',
      },
      {
        id: 'sales_by_product',
        label: 'Sales by Product',
        chartKey: 'sales_by_product',
        factName: 'units_sold',
        metrics: ['total_units_sold', 'total_revenue'],
        dimensions: ['time', 'product'],
        module: 'sales_inventory',
      },
      {
        id: 'sales_by_customer',
        label: 'Sales by Customer',
        chartKey: 'sales_by_customer',
        factName: 'units_sold',
        metrics: ['total_units_sold', 'total_revenue'],
        dimensions: ['time', 'customer'],
        module: 'sales_inventory',
      },
      {
        id: 'sales_performance',
        label: 'Sales Performance',
        chartKey: 'sales_performance',
        factName: 'sales_performance',
        metrics: [
          'total_units_sold',
          'total_revenue',
          'average_order_value',
          'conversion_rate',
        ],
        dimensions: ['time', 'product', 'customer'],
        module: 'sales_inventory',
      },
      {
        id: 'new_customers',
        label: 'New Customers',
        chartKey: 'new_customers',
        factName: 'new_customers',
        metrics: ['new_customers'],
        dimensions: ['time'],
        module: 'sales_inventory',
      },
      {
        id: 'purchases',
        label: 'Purchases',
        chartKey: 'purchases',
        factName: 'units_purchased',
        metrics: ['total_units_purchased', 'total_cost'],
        dimensions: ['time', 'product', 'vendor'],
        module: 'sales_inventory',
      },
    ],
  },
  {
    id: 'budget_analytics',
    label: 'Budget Analytics',
    icon: Calculator,
    submenus: [
      {
        id: 'budget_overview',
        label: 'Budget Overview',
        chartKey: 'budget_overview',
        factName: 'budget',
        metrics: ['budget_amount', 'actual_amount', 'variance'],
        dimensions: ['time'],
      },
      {
        id: 'budget_by_department',
        label: 'Budget by Department',
        chartKey: 'budget_by_department',
        factName: 'budget',
        metrics: ['budget_amount', 'actual_amount'],
        dimensions: ['time', 'department'],
      },
      {
        id: 'budget_by_location',
        label: 'Budget by Location',
        chartKey: 'budget_by_location',
        factName: 'budget',
        metrics: ['budget_amount', 'actual_amount'],
        dimensions: ['time', 'location'],
      },
      {
        id: 'budget_variance',
        label: 'Budget Variance Analysis',
        chartKey: 'budget_variance',
        factName: 'budget',
        metrics: ['variance_percentage'],
        dimensions: ['time', 'category'],
      },
    ],
  },
];

export const reportData: ReportDataType = {
  collection: [
    {
      id: 'collection1',
      title: 'Collection Summary',
      description: 'Overview of all collections',
      category: 'collection',
    },
    {
      id: 'collection2',
      title: 'Outstanding Collections',
      description: 'List of pending collections',
      category: 'collection',
    },
  ],
  customer: [
    {
      id: 'customer1',
      title: 'Customer Activity',
      description: 'Customer transaction history',
      category: 'customer',
    },
    {
      id: 'customer2',
      title: 'Customer Insights',
      description: 'Analysis of customer behavior',
      category: 'customer',
    },
  ],
  disbursement: [
    {
      id: 'disbursement1',
      title: 'Payment Summary',
      description: 'Overview of all disbursements and payments',
      category: 'disbursement',
      dataType: 'payment',
    },
    {
      id: 'disbursement2',
      title: 'Pending Disbursements',
      description: 'List of pending disbursements',
      category: 'disbursement',
    },
  ],
  expense: [
    {
      id: 'expense1',
      title: 'Budget Utilization',
      description: 'Analysis of budget allocation and spending',
      category: 'expense',
      dataType: 'budget',
    },
    {
      id: 'expense2',
      title: 'Expense Categories',
      description: 'Breakdown of expenses by category',
      category: 'expense',
    },
  ],
  financial: [
    {
      id: 'financial1',
      title: 'Balance Sheet',
      description: 'Current financial position',
      category: 'financial',
    },
    {
      id: 'financial2',
      title: 'Profit & Loss',
      description: 'Revenue and expense summary',
      category: 'financial',
    },
    {
      id: 'financial3',
      title: 'Cash Flow Statement',
      description: 'Cash inflow and outflow analysis',
      category: 'financial',
    },
  ],
  inventory: [
    {
      id: 'inventory1',
      title: 'Inventory Status',
      description: 'Current inventory levels',
      category: 'inventory',
    },
    {
      id: 'inventory2',
      title: 'Stock Movement',
      description: 'Inventory movement analysis',
      category: 'inventory',
    },
  ],
  tax: [
    {
      id: 'tax1',
      title: 'Tax Summary',
      description: 'Overview of tax obligations',
      category: 'tax',
    },
    {
      id: 'tax2',
      title: 'VAT Report',
      description: 'Value-added tax analysis',
      category: 'tax',
    },
  ],
  vendor: [
    {
      id: 'vendor1',
      title: 'Vendor Performance',
      description: 'Analysis of vendor reliability',
      category: 'vendor',
    },
    {
      id: 'vendor2',
      title: 'Vendor Payments',
      description: 'Summary of payments to vendors',
      category: 'vendor',
    },
  ],
};

export const frequentReports: Report[] = [
  {
    id: 'financial1',
    title: 'Balance Sheet',
    description: 'Current financial position',
    category: 'financial',
  },
  {
    id: 'disbursement1',
    title: 'Payment Summary',
    description: 'Overview of all disbursements and payments',
    category: 'disbursement',
    dataType: 'payment',
  },
  {
    id: 'expense1',
    title: 'Budget Utilization',
    description: 'Analysis of budget allocation and spending',
    category: 'expense',
    dataType: 'budget',
  },
];
