import { FormQuestion, QuestionType } from "./types";

export const defaultQuestions: Record<QuestionType, Partial<FormQuestion>> = {
  text: {
    type: 'text',
    title: 'Add a message for approvers to review',
    description: '',
    required: false,
    mapping: '',
  },
  paragraph: {
    type: 'paragraph',
    title: 'Add a longer message for approvers to review',
    description: '',
    required: false,
    mapping: '',
  },
  boolean: {
    type: 'boolean',
    title: 'Yes or No?',
    description: '',
    required: false,
    mapping: '',
  },
  number: {
    type: 'number',
    title: 'Enter a number',
    description: '',
    required: false,
    mapping: '',
  },
  date: {
    type: 'date',
    title: 'Pick a date',
    description: '',
    required: false,
    mapping: '',
  },
  link: {
    type: 'link',
    title: 'Enter a link',
    description: '',
    required: false,
    mapping: '',
  },
  email: {
    type: 'email',
    title: 'Enter an email address',
    description: '',
    required: false,
    mapping: '',
  },
  single_select: {
    type: 'single_select',
    title: 'Choose one option',
    description: '',
    required: false,
    mapping: '',
    options: ['Option 1', 'Option 2'],
  },
  multi_select: {
    type: 'multi_select',
    title: 'Choose one or more options',
    description: '',
    required: false,
    mapping: '',
    options: ['Option 1', 'Option 2'],
  },
  file_upload: {
    type: 'file_upload',
    title: 'Upload a file',
    description: '',
    required: false,
    mapping: '',
  },
  address: {
    type: 'address',
    title: 'Enter an address',
    description: '',
    required: false,
    mapping: '',
  },
  contact: {
    type: 'contact',
    title: 'Enter a contact',
    description: '',
    required: false,
    mapping: '',
  },
  billing_contact: {
    type: 'billing_contact',
    title: 'Billing contact',
    description: '',
    required: true,
    mapping: '',
  },
  billing_address: {
    type: 'billing_address',
    title: 'Billing address',
    description: '',
    required: true,
    mapping: '',
  },
  net_payment_terms: {
    type: 'net_payment_terms',
    title: 'Net payment terms',
    description: '',
    required: true,
    mapping: '',
  },
  vendor_address: {
    type: 'vendor_address',
    title: 'Vendor address',
    description: '',
    required: true,
    mapping: '',
  },
  vendor_contact: {
    type: 'vendor_contact',
    title: 'Vendor contact',
    description: '',
    required: true,
    mapping: '',
  },
  promise_date: {
    type: 'promise_date',
    title: 'Promise date',
    description: '',
    required: true,
    mapping: '',
  },
  shipping_date: {
    type: 'shipping_date',
    title: 'Shipping date',
    description: '',
    required: true,
    mapping: '',
  },
  ship_to_address: {
    type: 'ship_to_address',
    title: 'Ship to address',
    description: '',
    required: true,
    mapping: '',
  },
  memo: {
    type: 'memo',
    title: 'Memo',
    description: '',
    required: false,
    mapping: '',
  },
  attachments: {
    type: 'attachments',
    title: 'Attachments',
    description: '',
    required: false,
    mapping: '',
  },
  vendor: {
    type: 'vendor',
    title: 'Specify the vendor for this request',
    description: '',
    required: true,
    mapping: '',
  },
};